artifacts_root: /home/arvind/Python/DL/zenml/artifacts

data_ingestion:
  root_dir: /home/arvind/Python/DL/datasets/datav1
  data_source: /home/arvind/Python/DL/zenml/datasets/data3  #https://universe.roboflow.com/ds/xVFScOg5j2?key=93Tq5paN8Z
  unzip_dir: /home/arvind/Python/DL/datasets/datav1/v2
  classes: ['employee','security','cleaning staff']

# face dset - https://universe.roboflow.com/ds/bs9gtF70wF?key=IXirQnvG0W
# timy-dset "https://universe.roboflow.com/ds/xVFScOg5j2?key=93Tq5paN8Z"
# E waste dataset "https://universe.roboflow.com/ds/i02h52wl6q?key=ZM0MEFLZ5R"
# COCO data     "https://public.roboflow.com/ds/fYqIOuhVKK?key=sAOM4f2h70"

#new custom dataset
custom_dataset:
  classes: []
  new_data_path: Data/data_ingestion
  dataset_name: version1

train_log_config:  
  model: yolov8n.pt # choices="yolov8n","yolov8s","yolov8m","yolov8l","yolov8x"
  mlflow_uri: http://127.0.0.1:5000
  experiment_name: demov8
  model_name: dem

param:
  optimizer: auto # other choices=['auto', 'SGD', 'Adam', 'AdamW', 'RMSProp']
  lr0: 0.03     
  save_period: -1
  batch: 10
  epochs: 3
  resume: False
  seed: 0
  imgsz: 640
  cfg: /home/arvind/Python/DL/zenml/config/cfg.yaml

threshold:
  mAP50: 0.02   #0.02
  mAP50_95: 0.01

evaluation:
  name: dem
  version: 
  data_source: /home/arvind/Python/DL/datasets/datav1/test/images
  save_dir: /home/arvind/Python/DL/datasets/datav1/test/images

# evaluation:
#   path_of_model: artifacts/trained_model/Trainedv8.pt
#   trainig_data: artifacts/data_ingestion/data
#   mlflow_uri: https://dagshub.com/Arvindnbr/MLOPs.mlflow