artifacts_root: /home/arvind/Python/DL/zenml/artifacts
# run mlflow server mlflow server --backend-store-uri /home/server02/MLOPs/MLOPS_artifacts
#malabar gold

data_ingestion:
  root_dir: /home/server02/MLOPs/Datasets/Al-Safeer
  data_source: /home/server02/MLOPs/Datasets/Al-Safeer/dataset
  unzip_dir: /home/server02/MLOPs/Datasets/Al-Safeer/AlsafeerV1
  classes: ['cashier','customer','staff','cart','security']
  test_set: True

#new custom dataset
custom_dataset:
  classes: []
  new_data_path: /home/server02/MLOPs/Datasets/Al-Safeer
  dataset_name: version1

train_log_config:  
  model: yolov8m.pt                     
  mlflow_uri: http://127.0.0.1:5000
  experiment_name: Alsafeer
  model_name: AlsafeerV1

param:
  optimizer: SGD # other choices=['auto', 'SGD', 'Adam', 'AdamW', 'RMSProp']
  lr0: 0.001     
  save_period: -1
  batch: -1
  epochs: 150
  resume: False
  seed: 0
  imgsz: 640
  patience: 50
  cache: 'False'
  workers: 8
  cos_lr: True
  close_mosaic: 10
  amp: True
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8 
  warmup_bias_lr: 0.01  
  box: 7.5
  cls: 0.5        
  #augmentation
  hsv_h: 0.015             
  hsv_s: 0.7                 
  hsv_v: 0.4               
  degrees: 0.0                
  translate: 0.1             
  scale: 0.7                
  shear: 0.1                 
  perspective: 0.0          
  flipud: 0.0               
  fliplr: 0.5               
  bgr: 0.0                  
  mosaic: 1.0               
  mixup: 0.0                 
  copy_paste: 0.0            
  auto_augment: 'augmix' 
  erasing: 0.4
  crop_fraction: 1.0 
  freeze: 0

threshold:
  mAP50: 0.02   #0.02
  mAP50_95: 0.01  

evaluation:
  name: dem
  version: 
  data_source: /home/arvind/Python/DL/datasets/datav1/data.yaml
  save_dir: /home/arvind/Python/DL/datasets/validation
